version : '3.8'

services:

  firstquery_db:
    image: redis

  secondquery_db:
    image: mongo

  eventstore_db:
    image: postgres

  eventbus:
    image: rabbitmq:3-management-alpine

  command_api:
    image: command_api:1.0
    build:
      context: .
      dockerfile: Command/Command.API/Dockerfile

  secondaryquery_api:
    image: secondaryquery_api:1.0
    build: 
      context: .
      dockerfile: Query/SecondQueryProject/Dockerfile




volumes:
  postgres_data:
  mongo_data: