version: '3.8'

services:

  eventstore_db:
    container_name: eventstore_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - 7000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  eventbus:
    container_name: eventbus
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin1234
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"


  command_api:
    image: command_api:1.0
    container_name: command_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
