version : '3.8'

services:

  eventstore_db:
    image: postgres

  eventbus:
    image: rabbitmq:3-management-alpine

  command_api:
    image: command_api:1.0
    build:
      context: .
      dockerfile: Command/Command.API/Dockerfile




volumes:
   postgres_data: